### ISSUE TITLE
Warning nach dem Upload

### ISSUE THREAD

**Issue by Ik4ru5** [fsi-hska/examPlugin#13]
nach dem Upload wird folgende Warining angezeigt:
[phpBB Debug] PHP Warning: in file /var/www/hska.info/dokuwiki/lib/plugins/klausuren/helper/download.php on line 20: array_filter() expects parameter 1 to be array, null given

Warning ist aufgetreten beim Uploaden von HPC-Klausuren

**Comment by Geruhn** [comment]
Vermutlich längst gefixt ( in Zeile 15: if ($dozenten==NULL) $dozenten=array();)
