### ISSUE TITLE
Aktuell wird Professor als nicht gesetzt angezeigt, obwohl es gesetzt ist.

### ISSUE THREAD

**Issue by memo42** [fsi-hska/examPlugin#18]

**Comment by memo42** [comment]
In allen Commits nach 708638e0b585c8889e84804f1854ab617989b6be

**Comment by Geruhn** [comment]
Die Methode getAllDozenten() lief nicht korrekt ab, da der übergebene $doctype Parameter leer war. Dies folgte aus einem leeren $data['doctype'], welches zirkulär übergeben wird, da auch der doctype-Wert im Upload-Formular schon "" ist.
Mögliche andere Lösungen: 
- gescheit fixen: Dateistruktur ändern und alle Fächer in "/var/www/hska.info/dokudata/media/vorlesungen/unterlagen" auf klausuren/ und loesungen/ Ordner aufteilen. (Bsp.: /var/www/hska.info/dokudata/media/vorlesungen/unterlagen/klausuren/info2/info2_2008_ss_klausur.pdf und /var/www/hska.info/dokudata/media/vorlesungen/unterlagen/loesungen/info2/info2_2008_ss_loesung.pdf)
- reverten auf Implementation ohne doctype
